network:
    ethernets:
        ens3:
            dhcp4: true
            addresses: 
                - 10.61.17.34/27
                - 10.61.17.65/27
                - 10.61.17.97/27
    version: 2
