network:
    ethernets:
        ens3:
            dhcp4: true
            addresses:
                - 10.61.17.66/27
        routes:
            - to: 10.61.17.0/25
              via: 10.61.17.65
    version: 2
